# Generated by Django 4.0.3 on 2022-03-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Famous_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('author_of_publication', models.CharField(max_length=30, verbose_name='Имя автора публикации')),
            ],
            options={
                'verbose_name': 'Знаменитый писатель',
                'verbose_name_plural': 'Знаменитые писатели',
            },
        ),
    ]
