# Generated by Django 4.0.2 on 2022-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dopcont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
