# Generated by Django 4.0.2 on 2022-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dopcont'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous_persons',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
