# Generated by Django 4.0.2 on 2022-04-07 13:44

from django.db import migrations

def populate_posts_slug_field(apps, schema_editor):
        for post in apps.get_model('main.post'):
            post.slug = 'abay'
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_famous_persons_slug'),
    ]

    operations = [
        migrations.RunPython(populate_posts_slug_field, migrations.RunPython.noop),
    ]


