# Generated by Django 4.0.2 on 2022-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220407_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous_persons',
            name='slug',
            field=models.SlugField(default=123, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
