# Generated by Django 4.0.2 on 2022-04-07 14:27

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_famous_persons_slut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famous_persons',
            name='slut',
        ),
        migrations.AlterField(
            model_name='famous_persons',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True, verbose_name='URL'),
        ),
    ]
