# Generated by Django 4.0.2 on 2022-04-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_famous_persons_slut_alter_famous_persons_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous_persons',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
